# Generated by Django 2.0.3 on 2018-05-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180530_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecteditem',
            old_name='menuitem',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='products',
            new_name='items',
        ),
    ]
