# Generated by Django 2.0.3 on 2018-05-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180530_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecteditem',
            old_name='selectedproduct',
            new_name='selection',
        ),
    ]
