# Generated by Django 2.0.3 on 2018-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180530_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('primary', 'Primary'), ('components', 'Components'), ('additions', 'Additions')], default='primary', max_length=15),
        ),
    ]
